version: '3'
services:
  db:
    image: postgres:11.3-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - 5432:5432
#  testdb:
#     image: postgres:11.3-alpine
#     env_file: .env
#     restart: unless-stopped
#     ports:
#       - 5432:5432

#    volumes:
#      - "/data/luckysevens777/calendar/mysql:/var/lib/mysql"
  nginx:
    build: ./webpage
    container_name: nginx
    volumes:
      - ./webpage/front/.:/code
    tty: true
    ports:
      - "80:80"
  backend:
    build: ./back
    container_name: golang_backend
    ports:
      - "3000:3000"
