version: '3'
services:
  db:
    image: postgres:11.3-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - 5432:5432

#    volumes:
#      - "/data/luckysevens777/calendar/mysql:/var/lib/mysql"
