version: '3'
services:
  nginx:
    build: ./webpage
    container_name: nginx
    volumes: 
      - ./webpage/front/.:/code
    tty: true
    ports: 
      - "80:80"
      - "443:443"
  db:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ross"
      MYSQL_DATABASE: "is"
      MYSQL_USER: "the" 
      MYSQL_PASSWORD: "coolest"
