version: '3'
services:
  db:
    image: postgres:11.3-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - /data/LuckySevens/Calendar-App/postgres:/var/lib/postgresql/data
  nginx:
    build: ./webpage
    container_name: nginx
    volumes:
      - ./webpage/front/.:/code
    tty: true
    ports:
      - "80:80"
  backend:
    build: ./back
    container_name: golang_backend
    ports:
      - "10000:10000"
  backdocs:
    build: ./back
    command: godoc -http=:6060
    ports:
      - "6060:6060"
