FROM golang
WORKDIR /go/src/Calendar-App/back
COPY . .
#RUN go run main.go



































#WORKDIR /usr/local/go/src/Calendar-App/back/processing
#COPY processing .
#WORKDIR /go/src/Calendar-App/back/model
#COPY model .
#WORKDIR /usr/local/go/src/Calendar-App/back/model
#COPY model .
#WORKDIR /go
#COPY main.go .
